### ISSUE TITLE
Installing jax with grpcio results in an old not working (jax,jaxlib) combination

### ISSUE THREAD

**Issue by traversaro** [conda-forge/jax-feedstock#102]
### Comment:

~~~
traversaro@IITICUBLAP257:~$ mamba create -n test grpcio jax

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['grpcio', 'jax']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
Transaction

  Prefix: /home/traversaro/mambaforge/envs/test

  Updating specs:

   - grpcio
   - jax


  Package                   Version  Build                Channel                    Size
───────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex               0.1  conda_forge          conda-forge/linux-64     Cached
  + _openmp_mutex               4.5  2_gnu                conda-forge/linux-64     Cached
  + absl-py                   1.2.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + bzip2                     1.0.8  h7f98852_4           conda-forge/linux-64     Cached
  + c-ares                   1.18.1  h7f98852_0           conda-forge/linux-64     Cached
  + ca-certificates       2022.9.24  ha878542_0           conda-forge/linux-64     Cached
  + etils                     0.8.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + grpc-cpp                 1.48.1  h30feacc_1           conda-forge/linux-64     Cached
  + grpcio                   1.48.1  py310hc32fa93_1      conda-forge/linux-64     Cached
  + importlib_resources       5.9.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + jax                      0.3.14  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + jaxlib                   0.1.75  py310hb5077e9_0      conda-forge/linux-64     Cached
  + ld_impl_linux-64         2.36.1  hea4e1c9_2           conda-forge/linux-64     Cached
  + libabseil            20220623.0  cxx17_h48a1fff_4     conda-forge/linux-64     Cached
  + libblas                   3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libcblas                  3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libffi                    3.4.2  h7f98852_5           conda-forge/linux-64     Cached
  + libgcc-ng                12.1.0  h8d9b700_16          conda-forge/linux-64     Cached
  + libgfortran-ng           12.1.0  h69a702a_16          conda-forge/linux-64     Cached
  + libgfortran5             12.1.0  hdcd56e2_16          conda-forge/linux-64     Cached
  + libgomp                  12.1.0  h8d9b700_16          conda-forge/linux-64     Cached
  + liblapack                 3.9.0  16_linux64_openblas  conda-forge/linux-64     Cached
  + libnsl                    2.0.0  h7f98852_0           conda-forge/linux-64     Cached
  + libopenblas              0.3.21  pthreads_h78a6416_3  conda-forge/linux-64     Cached
  + libprotobuf              3.21.7  h6239696_0           conda-forge/linux-64     Cached
  + libsqlite                3.39.4  h753d276_0           conda-forge/linux-64     Cached
  + libstdcxx-ng             12.1.0  ha89aaad_16          conda-forge/linux-64     Cached
  + libuuid                  2.32.1  h7f98852_1000        conda-forge/linux-64     Cached
  + libzlib                  1.2.12  h166bdaf_4           conda-forge/linux-64     Cached
  + ncurses                     6.3  h27087fc_1           conda-forge/linux-64     Cached
  + numpy                    1.23.3  py310h53a5b5f_0      conda-forge/linux-64     Cached
  + openssl                   3.0.5  h166bdaf_2           conda-forge/linux-64     Cached
  + opt_einsum                3.3.0  pyhd8ed1ab_1         conda-forge/noarch       Cached
  + pip                      22.2.2  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + python                   3.10.6  ha86cf86_0_cpython   conda-forge/linux-64     Cached
  + python-flatbuffers          2.0  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + python_abi                 3.10  2_cp310              conda-forge/linux-64     Cached
  + re2                  2022.06.01  h27087fc_0           conda-forge/linux-64     Cached
  + readline                  8.1.2  h0f457ee_0           conda-forge/linux-64     Cached
  + scipy                     1.9.1  py310hdfbd76f_0      conda-forge/linux-64     Cached
  + setuptools               65.4.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + six                      1.16.0  pyh6c4a22f_0         conda-forge/noarch       Cached
  + tk                       8.6.12  h27826a3_0           conda-forge/linux-64     Cached
  + typing_extensions         4.3.0  pyha770c72_0         conda-forge/noarch       Cached
  + tzdata                    2022d  h191b570_0           conda-forge/noarch       Cached
  + wheel                    0.37.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + xz                        5.2.6  h166bdaf_0           conda-forge/linux-64     Cached
  + zipp                      3.8.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + zlib                     1.2.12  h166bdaf_4           conda-forge/linux-64     Cached

  Summary:

  Install: 49 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate test

To deactivate an active environment, use

     $ mamba deactivate

traversaro@IITICUBLAP257:~$ mamba activate test
(test) traversaro@IITICUBLAP257:~$ python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/traversaro/mambaforge/envs/test/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/traversaro/mambaforge/envs/test/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/traversaro/mambaforge/envs/test/lib/python3.10/site-packages/jax/_src/config.py", line 29, in <module>
    from jax._src import lib
  File "/home/traversaro/mambaforge/envs/test/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 94, in <module>
    version = check_jaxlib_version(
  File "/home/traversaro/mambaforge/envs/test/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 83, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib is version 0.1.75, but this version of jax requires version >= 0.3.7.
>>>
~~~

The issue is probably some old jaxlib build that does not have the correct constraints I guess, I encountered the issue in https://github.com/conda-forge/staged-recipes/pull/20411 .

**Comment by traversaro** [comment]
Just tested know, it works fine at the moment, I guess it can happen again if a new `grpcio` is released  for which there is no jax compatible, but for now let's close until this happens again.
